### ISSUE TITLE
Component Diagram - KYC

### ISSUE THREAD

**Issue by arealclimber** [CAFECA-IO/ASICEX#15]
-----
reference
- [Wireframe](https://www.figma.com/file/A80wkYEVz26lYbtIJhFoGw/ASICEX?type=design&node-id=2-2&mode=design&t=rjLqQotNZRoROA7B-0)｜[系統架構書](https://docs.google.com/document/d/1jDg2fw-cn0Z-BapNCV_b0lTu6HVrJLdZnWu8g9sNNRk/edit#heading=h.2isx8p1jo9tw)｜[Class Diagram](https://lucid.app/lucidchart/8257bc36-dab5-4f91-acab-6db1387a2015/edit?viewport_loc=-9119%2C-7479%2C5727%2C3810%2CHWEp-vi-RSFO&invitationId=inv_c062eeb6-9d01-445f-996e-b44c04d19f58)（[DOC](https://github.com/CAFECA-IO/Documents/blob/main/AEX/AEXCD00001.md)）

**Comment by Julian0701** [comment]
- take 1 hr, remain 3 hrs

**Comment by Julian0701** [comment]
![ASICEX Component Diagram - KYC](https://github.com/CAFECA-IO/ASICEX/assets/114177573/a4c0e780-ee20-4022-bde6-378a7581564f)

- take 3 hrs

**Comment by Julian0701** [comment]
![ASICEX Component Diagram - KYC](https://github.com/CAFECA-IO/ASICEX/assets/114177573/dffcad16-23f2-42f7-b0a6-5ebcc966390e)
- 加上 wireframe code
