### ISSUE TITLE
Component Diagram - General data

### ISSUE THREAD

**Issue by arealclimber** [CAFECA-IO/ASICEX#17]
- [x] 通知
- [x] landing page 
-----
reference
- [Wireframe](https://www.figma.com/file/A80wkYEVz26lYbtIJhFoGw/ASICEX?type=design&node-id=2-2&mode=design&t=rjLqQotNZRoROA7B-0)｜[系統架構書](https://docs.google.com/document/d/1jDg2fw-cn0Z-BapNCV_b0lTu6HVrJLdZnWu8g9sNNRk/edit#heading=h.2isx8p1jo9tw)｜[Class Diagram](https://lucid.app/lucidchart/8257bc36-dab5-4f91-acab-6db1387a2015/edit?viewport_loc=-9119%2C-7479%2C5727%2C3810%2CHWEp-vi-RSFO&invitationId=inv_c062eeb6-9d01-445f-996e-b44c04d19f58)（[DOC](https://github.com/CAFECA-IO/Documents/blob/main/AEX/AEXCD00001.md)）

**Comment by Julian0701** [comment]
![ASICEX Component Diagram - General data](https://github.com/CAFECA-IO/ASICEX/assets/114177573/6db663a4-431d-4e27-a14b-63cd1fd14540)
- take 3 hrs
