### ISSUE TITLE
Component Diagram - Assets

### ISSUE THREAD

**Issue by arealclimber** [CAFECA-IO/ASICEX#18]
-----
reference
- [Wireframe](https://www.figma.com/file/A80wkYEVz26lYbtIJhFoGw/ASICEX?type=design&node-id=2-2&mode=design&t=rjLqQotNZRoROA7B-0)｜[系統架構書](https://docs.google.com/document/d/1jDg2fw-cn0Z-BapNCV_b0lTu6HVrJLdZnWu8g9sNNRk/edit#heading=h.2isx8p1jo9tw)｜[Class Diagram](https://lucid.app/lucidchart/8257bc36-dab5-4f91-acab-6db1387a2015/edit?viewport_loc=-9119%2C-7479%2C5727%2C3810%2CHWEp-vi-RSFO&invitationId=inv_c062eeb6-9d01-445f-996e-b44c04d19f58)（[DOC](https://github.com/CAFECA-IO/Documents/blob/main/AEX/AEXCD00001.md)）

**Comment by Julian0701** [comment]
![ASICEX Component Diagram - Assets](https://github.com/CAFECA-IO/ASICEX/assets/114177573/5b1c00ec-29bb-4ac6-8b10-b37923b83870)
- take 2 hrs

**Comment by arealclimber** [comment]
1. 關於 MarketSection component 的部分，如果是指 Market Linear Trend 的區塊，這邊與市場無關，是用戶自己的資產紀錄，所以不需要 SpotTradeMarketCtx，參考下圖，另外建議更改 MarketSection 的命名避免混淆

![image](https://github.com/CAFECA-IO/ASICEX/assets/20677913/b809da5f-6043-4adc-b408-4e6bc6e0c940)

2. 用戶資產需要轉換成特定法幣，所以需要存取 GeneralCtx 的匯率資料，這邊的元件關係有所缺失

**Comment by arealclimber** [comment]
@StrawHo Market Linear Trend 這個標題好像不能描述 “表格化跟圖形化用戶自己操作資產的紀錄” 這個功能，會造成混淆，建議可以用 "Personal Asset Tracking and Analysis" 或 "User Asset Management Dashboard" 之類的詞語描述

**Comment by StrawHo** [comment]
好，我修改一下

**Comment by Julian0701** [comment]
![ASICEX Component Diagram - Assets](https://github.com/CAFECA-IO/ASICEX/assets/114177573/055e4c90-fca4-44ee-92f4-333d6d1c3235)
- 加上 wireframe code
