### ISSUE TITLE
Sequence Diagram - Registration, Login and Logout

### ISSUE THREAD

**Issue by arealclimber** [CAFECA-IO/ASICEX#20]
-----
reference
- [Wireframe](https://www.figma.com/file/A80wkYEVz26lYbtIJhFoGw/ASICEX?type=design&node-id=2-2&mode=design&t=rjLqQotNZRoROA7B-0)｜[系統架構書](https://docs.google.com/document/d/1jDg2fw-cn0Z-BapNCV_b0lTu6HVrJLdZnWu8g9sNNRk/edit#heading=h.2isx8p1jo9tw)｜[Class Diagram](https://lucid.app/lucidchart/8257bc36-dab5-4f91-acab-6db1387a2015/edit?viewport_loc=-9119%2C-7479%2C5727%2C3810%2CHWEp-vi-RSFO&invitationId=inv_c062eeb6-9d01-445f-996e-b44c04d19f58)（[DOC](https://github.com/CAFECA-IO/Documents/blob/main/AEX/AEXCD00001.md)）

**Comment by Julian0701** [comment]
![ASICEX121](https://github.com/CAFECA-IO/ASICEX/assets/114177573/9d1d6da8-df3f-4054-8808-17a772af7e3d)

- take 2 hrs, remain 3 hrs

**Comment by Julian0701** [comment]
- [ASICEX122-Login](https://sequencediagram.org/index.html#initialData=C4S2BsFMAIEEGUCSBhAogDWgCgIwCY8BaAGQHsBzEAOwEoAoOgQwGNhSAnaAVQGdJ2GAB0btQzEMKrBoZSlQAKjcpABCpACYBPOsNEhxk6b37JgADx0ixExlOgB5Qf0ahSVRuACytpZAC2kFKmFnQAxIDeboCminTG7IQAfLLUispqWgBcgcD80P6MIODQAGTQwjw8AO4c6gA00Lbq0Mzg+gDW0Dwg5FTQ1NAARgCuwGxUTKwgAG4uMLHjoNPZMhTJvmnaSQprGpoJscHp4CtUKpqwzMykg1JYeQV1ZZXV9CwLM9x87MExn8F7v+Z0oJ2KRmJBytB2ODBG4+NA2JDwYNwMAGBFIoB6M0AZCqABCNAPlKTBRoQA7JBGJAAGbE5ZyDqDC7gngU5HgbT7cyEBKbFKqHbpHj0sHlZmFKE8GFUPh0bnbLT-fj8gAWpAqDnakkg4Domrhm2gFPyUHUPxMHK5xx563SBoKkEaYolUvRgHpkwAlUYBCa0AHqaABiVACoJgCg5QAKaVgAMzu+ikQTAUIATgArBTmIxGnqbUboCH4SAAjxpRbZbt4o5nK53F4fMoAkFARSoZAAF6QLAgWr6kGN2h0YvsFwgNwebzuStZP5Fpw90sDiv+EeA4GgxmI8WwmAIsXI1Hd3v98tDmfVsycxL51J8h0rvNyS07eXsJUq+oXK52RWMHgDSCBNukDvQHM8XxtSoY0ZVPOV4lie9VQqEQqGoch4UgMxpA4LMc2gUgKX1Q07WgI5aRcbI-CjXNAmNOggA)
- take 2 hrs

**Comment by Julian0701** [comment]
- [ASICEX123-Logout](https://sequencediagram.org/index.html#initialData=C4S2BsFMAIEEGUCSBhAogDWgCgIwCYBmAWgBkB7AczIFdgBKAKAYEMBjYMgJ2gFUBnSJyYAHZp1CsQogHbBoAOWYA3AEZiGo8SEky5-QcmAAPJgGJA3m6AvxQb7ORAHyLVYgFytw2gNbRwlaDTkVWg5pBic1O3tbQyMXXypaLEZo4wcU2OFOMlZIPj5oTlzhMmkBaA4C3OpwYBsBThiiB3DXQr5i0sgw5Qi0+pcs2kFoYWo+AAtysmhxsgBbGFEKGCYgA)
- take 10 mins
