### ISSUE TITLE
Sequence Diagram - Withdrawal

### ISSUE THREAD

**Issue by arealclimber** [CAFECA-IO/ASICEX#22]
-----
reference
- [Wireframe](https://www.figma.com/file/A80wkYEVz26lYbtIJhFoGw/ASICEX?type=design&node-id=2-2&mode=design&t=rjLqQotNZRoROA7B-0)｜[系統架構書](https://docs.google.com/document/d/1jDg2fw-cn0Z-BapNCV_b0lTu6HVrJLdZnWu8g9sNNRk/edit#heading=h.2isx8p1jo9tw)｜[Class Diagram](https://lucid.app/lucidchart/8257bc36-dab5-4f91-acab-6db1387a2015/edit?viewport_loc=-9119%2C-7479%2C5727%2C3810%2CHWEp-vi-RSFO&invitationId=inv_c062eeb6-9d01-445f-996e-b44c04d19f58)（[DOC](https://github.com/CAFECA-IO/Documents/blob/main/AEX/AEXCD00001.md)）

**Comment by Julian0701** [comment]
![ASICEX141](https://github.com/CAFECA-IO/ASICEX/assets/114177573/85f1e0e0-b960-4137-a6ab-794ce572b8ba)

- 完成 14-1，還剩 14-2 人工審核
- take 5 hrs, remain 2 hrs

**Comment by Julian0701** [comment]
- take 1 hr
- 調整 ASICEX141

**Comment by Julian0701** [comment]
[ASICEX142 - Withdrawal(Admin)](https://sequencediagram.org/index.html#initialData=C4S2BsFMAIEEGUCSBhAogDWgCgIwBYAmAWgHUwALAEwCcBDAd1vC1koFsQA7ASm4Cg+tAMbAA9tTjsuAgA61qoISDmdgkjp2Si2M0Z0iq+chSCUq1AMQASAWXhH5i5bVXQAIgAV0Dk2ZdrYVAA5AQBiAHFINWpIAEcAV0gAZzVKWmBaPk5RYBhRADdICVYNaFCYygAuHAJiABlRAHNpYVB89JgS6S7OIgA+Hq0dPQNgSuRwUwBraBj8kEh6WbjElKToDIAjQREQdtz1LiHdfUNB7RPR-us7Ssi1egoaBiZlhOTgJJ22jugb+z4-yI-XOw1OYxiSROSUgfFBl1UIKknEqwGoiTCPWW80WXyYwFCAHZILRIAAzQnQABKKw+0DkSRhlDhyKRGmOI1U40mQhmDKZ0E28WAYk4LPZF05wGutnglQ81FEQmS60ewCodCWYmgjHAUDUtEoNBVgNl-U86HG5BcjRgbgAQt89r8LXwLSDgpV4AZKDqnprXkl4kJlZBfdlQGTTOkQHo4cFgQNkRzwZVIdDYfCpWyuKj0bDWs6DoEQpBwDDqbSUtBKKJktAI-TaIyw+KuDnNJLUxNpht4tRODXRPRB0KRXGs+DzV4rTa7Y73QNPd7OL61RqXuBoGTaCAoOGciAo0IYxOEx2U6M08kM23O2CrkmNHmMT6BEA)
- take 2 hrs
