### ISSUE TITLE
Sequence Diagram - Deposit

### ISSUE THREAD

**Issue by arealclimber** [CAFECA-IO/ASICEX#23]
-----
reference
- [Wireframe](https://www.figma.com/file/A80wkYEVz26lYbtIJhFoGw/ASICEX?type=design&node-id=2-2&mode=design&t=rjLqQotNZRoROA7B-0)｜[系統架構書](https://docs.google.com/document/d/1jDg2fw-cn0Z-BapNCV_b0lTu6HVrJLdZnWu8g9sNNRk/edit#heading=h.2isx8p1jo9tw)｜[Class Diagram](https://lucid.app/lucidchart/8257bc36-dab5-4f91-acab-6db1387a2015/edit?viewport_loc=-9119%2C-7479%2C5727%2C3810%2CHWEp-vi-RSFO&invitationId=inv_c062eeb6-9d01-445f-996e-b44c04d19f58)（[DOC](https://github.com/CAFECA-IO/Documents/blob/main/AEX/AEXCD00001.md)）

**Comment by Julian0701** [comment]
- [ASICEX151](https://sequencediagram.org/index.html#initialData=C4S2BsFMAIEEGUCSBhAogDWgCgIwFYcBaAEUgAcB7AZzAEoAoegQwGNgKAnaAVSsg8ZkmHUCxBCAdsGilKNYABUmAI3pCRIMZOkBxcBWVNwyYAA81w0eKZSefDifPqr26ADEAEgFl4jCRWAYCgA3fjswgGIOSAATAC4cACZEwgAZCgBzEAlGXn5CAD5ZajAlZTjIKTCmGJjoqipoADJoJgBbCgBXKQAaVokY6BZwTQBraCpO5TawaGVO4HYc1lBgpkDwgRWQNY3i+TL6fdKVQr0DI0c44JAaZShj4C8KGKMsBm3dmHPDYzN6H6XMyEQp5DhxYAcTqQRgRQCACYAvxUApoqARcTAMyugGmo+hgs76X5XYZjIYUCQAMxAHDacwWSwBeKBpmguIuf1M11uIHukHSNWyGWer3A7zpLMcoPsVxi5BKwCwNTqkAaHzYO3WMDBjlhgHJNQCyGajAADpgEDIuHubzwaCALrlAKe6gEvtQAcFsxwMAIgB2SBMSCkl3QVLCDIwdpdWxSuRgXIS4EFTw+OJ8AbQEMy6DRACO0KowGYKq+pp89Gj8BBBQ1ZghUJhUs+atzvnokHAfGg8DaRnArQ63Wkifk2IjjPF-El0vkwsqMXDg8jgNZ7LuUC8iqoTH9AreDGnYoH4Mh0PoQA)
- take 2 hrs, remain 2 hrs

**Comment by Julian0701** [comment]
- [ASICEX152](https://sequencediagram.org/index.html#initialData=C4S2BsFMAIEEGUCSBhAogDWgCgIwFYAmAWgBFIAHAewGcwtYATAWxADsBKdgKC4EMBjYJQBOcZmx7lew0PxBTWwMS1bJKTKq0iKuUmSDkKlAMQASAWXi7ps+b0XRkAJUvX9h+0pIAFdG9tGcKgAcjwAxADikErCkACOAK6Q1EoMvMC8XKyUwDCUAG6Qoowq0GGxDABcOATEADKUAOYSJWxEAHytquqa2sCVyOAGANbQsfkgkADuY-FJKdTQGQBGfIIg+ekwXWoalFo6Oz37fR1mlpVRqRQ0YLOJycDUa6CbudDnVlyfRB1Hewd+rFqJpqJAuP9eoo-uJWJVgMIkuEurMJtNnrxwMAwgB2SC8SAAMxx0Ccc0e0Ck1DBDAhsJhKl2UP6gxGlN41MgDGgywSwCErDpjOOgLOFnglW8wko-GSiwYN1oSm+4o6PnQAwAFvZGjASAAhLgKgSvLYfcUvDZm9VcdV-EKVeDabkKqhK6DUBL8WVc6DZUCEgzpED7S1vbYhI349bh6A22AhX6dWFMk6KSrA0Hg40xs0J0KQtPABlseGI8FcSDgMGk8kpaAMSjJP05dmc2ldEvdAF9AZDfijYAJYSsBuUKaj3n80OF0XtZwXMlUGSzbmE8C8Rphs0Lqy7tW+LU6vWGnOm9677fvG12zoOp2sF2Ku6E3ggKDc-0gQP8YOhk1Wu8+ZRgBsbxomXapoCGbJFmIG5kBkazqcyYqGWSLOjwQA)
- take 2 hrs
